#!/usr/bin/env bash
# Run the parity battery: one demo invocation per capability, and assert on
# what each one produced rather than on the demo merely having run.
#
# Usage, from the repo root, with CEF_PATH pointing at the CEF distribution:
#
#   RUN_CMD="cargo run -q -p demo-weld-linux" scripts/parity-battery.sh
#   RUN_CMD="cargo run -q -p demo-weld-win"   scripts/parity-battery.sh
#   RUN_CMD="./target/bundle/demo-weld-mac.app/Contents/MacOS/demo-weld-mac" \
#     scripts/parity-battery.sh
#
# macOS must run the bundled executable: CEF loads its framework relative to
# the .app, so `cargo run` cannot work there.
#
# Three verdicts, because two of them are easy to confuse:
#
#   PASS  the case's own receipt appeared and nothing failed
#   LIVE  the run was clean but this case has no receipt of its own, so it
#         proves the path did not break, not that the capability works
#   FAIL  the page did not load, the demo reported a failure, or the expected
#         receipt never appeared
#
# LIVE is deliberately not PASS. A capability whose only evidence is "the demo
# did not crash" has not been verified, and rolling it up as a pass is how a
# table ends up claiming more than was measured.
#
# Do not edit this file while it is running. Bash reads a script by byte
# offset as it executes, so an edit mid-run shifts everything underneath the
# interpreter and silently reruns or garbles later cases.
set -u

REPO="$(cd "$(dirname "$0")/.." && pwd)"

# Chromium wants a real file URL. Under Git Bash the repo path is /c/Users/...,
# which Chromium resolves as relative and answers ERR_FILE_NOT_FOUND for, so
# every probe case silently loads an error page and still imports frames.
# cygpath -m gives C:/Users/... which is what the URL needs.
case "$(uname -s)" in
MINGW* | MSYS* | CYGWIN*) PROBES="file:///$(cygpath -m "$REPO")/testing" ;;
*) PROBES="file://$REPO/testing" ;;
esac

OUT="${WELD_BATTERY_OUT:-$REPO/target/battery}"

# Scripted input is a staged sequence on a clock, not a queue that drains as
# fast as it can. demo-weld-*/src/scripted.rs gates stage N on
# `SETTLE + GAP * N` elapsed since the page became ready, with SETTLE 3s and
# GAP 2s, so stage N fires at 3 + 2N seconds:
#
#   0 touch   4 page-drag   5 click   6 wheel   7 key
#   8 IME     9 hide       10 show   11 devtools  12 right-click
#
# The last stage therefore needs ~27s plus however long the page took to load.
# Anything shorter silently drops the late stages, and the case then looks like
# a broken capability rather than a short clock: at 16s this battery reported
# IME, visibility, devtools and context as failures, and all four were fine.
CASE_SECS="${WELD_CASE_SECS:-34}"

: "${RUN_CMD:?set RUN_CMD to the demo invocation}"
: "${CEF_PATH:?set CEF_PATH to the CEF binary distribution}"
export CEF_PATH

# The demos do not agree on how they report. demo-weld-win uses eprintln!
# throughout, so it talks with no configuration; demo-weld-linux and
# demo-weld-mac put frame imports and navigation events behind `log`, which
# emits nothing at all unless RUST_LOG is set. Without this the battery sees
# only the eprintln! half on those two platforms and reports every title and
# frame receipt as missing, which reads exactly like a broken capability.
export RUST_LOG="${RUST_LOG:-info}"

mkdir -p "$OUT"
echo "battery: $RUN_CMD"
echo "cef:     $CEF_PATH"
echo "out:     $OUT"
echo

pass=0
live=0
fail=0

# run_case <name> <expect-regex|-> <env>...
run_case() {
  name="$1"
  expect="$2"
  shift 2
  log="$OUT/$name.log"

  env "$@" WELD_TIMEOUT_SECS="$CASE_SECS" $RUN_CMD >"$log" 2>&1
  code=$?

  # A case whose page never loaded still imports frames, of the error page,
  # and would otherwise read as a pass.
  # ERR_ABORTED is not a load failure: a case that exits on a frame count tears
  # the browser down mid-navigation and Chromium reports the cancelled load.
  if grep 'LoadError' "$log" 2>/dev/null | grep -qv 'ERR_ABORTED'; then
    fail=$((fail + 1))
    printf '  %-11s FAIL  page did not load %s\n' \
      "$name" "$(grep -ohE 'error_text: "[^"]*"' "$log" | grep -v ERR_ABORTED | head -1)"
    return
  fi

  # Match the whole line after "failed", not a restricted character class: the
  # macOS DevTools refusal reads `open_devtools() failed: ...`, and parentheses
  # are enough to slip past a tighter pattern and report a refusal as a pass.
  # move_focus is excluded: the demo calls it before on_after_created, so it
  # reports the browser as absent on every run and always has.
  failed=$(grep -ohE 'weld demo: [^:]*failed[^;]*' "$log" 2>/dev/null |
    grep -v move_focus | sort -u | cut -c1-90 | tr '\n' ';')
  if [ -n "$failed" ] || [ "$code" -ne 0 ]; then
    fail=$((fail + 1))
    printf '  %-11s FAIL  exit=%s %s\n' "$name" "$code" "${failed:-(no failure line)}"
    return
  fi

  if [ "$expect" = "-" ]; then
    live=$((live + 1))
    printf '  %-11s LIVE  ran clean, no receipt of its own\n' "$name"
    return
  fi

  got=$(grep -ohE "$expect" "$log" 2>/dev/null | sort -u | tail -2 | tr '\n' ';' | cut -c1-110)
  if [ -n "$got" ]; then
    pass=$((pass + 1))
    printf '  %-11s PASS  %s\n' "$name" "$got"
  else
    fail=$((fail + 1))
    printf '  %-11s FAIL  expected /%s/, absent\n' "$name" "$expect"
  fi
}

# Accelerated OSR paints on change, so a static page delivers one frame and
# goes quiet. Asking for "#2" makes a healthy import look broken on whichever
# platform happens not to get a spurious resize.
run_case import 'VALIDATION PASS|exit after 2 frames|imported frame #' WELD_EXIT_AFTER_FRAMES=2

run_case input 'title: "(key|wheel):[^"]*"' \
  WELD_URL="$PROBES/weld_input_probe.html" \
  WELD_CLICK_AT=120,120 WELD_WHEEL=400 WELD_KEY=a

run_case popup 'imported popup' WELD_URL="$PROBES/weld_select_probe.html" WELD_CLICK_AT=60,40
run_case find 'weld demo: find ' WELD_URL="$PROBES/weld_find_probe.html" WELD_FIND=needle
run_case zoom 'zoom level now|title: "w:[0-9]+"' WELD_URL="$PROBES/weld_zoom_probe.html" WELD_ZOOM=1
# The IME probe reports each phase, not the bare text: cstart:, cupdate:weld,
# cend:weld, textinput:weld, value:weld. Assert the committed value.
run_case ime 'title: "(value|textinput|cend):weld"' WELD_URL="$PROBES/weld_ime_probe.html" WELD_IME=weld
run_case context 'scripted right-click at' WELD_URL="$PROBES/weld_context_probe.html" WELD_RIGHT_CLICK_AT=60,40
run_case touch 'scripted touch at' WELD_URL="$PROBES/weld_drag_touch_probe.html" WELD_TOUCH_AT=120,120

# The drag must start on the probe's draggable element, which is fixed at CSS
# 500,350. Starting anywhere else grabs nothing, CEF never emits DragStarted,
# and the finish step it gates never runs. WELD_SCALE=1 pins physical pixels to
# CSS pixels so one coordinate is right on 1x and 2x panels alike.
run_case drag 'page drag finished as copy|title: "PAGE_DRAG:started"' \
  WELD_URL="$PROBES/weld_drag_touch_probe.html" \
  WELD_SCALE=1 WELD_PAGE_DRAG=520,370,620,420 WELD_FINISH_PAGE_DRAG=1

run_case download 'DownloadProgress \{[^}]*bytes_received' \
  WELD_URL="$PROBES/weld_download_probe.html" \
  WELD_CLICK_AT=60,40 WELD_DOWNLOAD_DIR="$OUT/downloads"

# The byte count is not the receipt; the file is. CEF reports 28 of 28 bytes
# for a transfer it never completes and never assigns a path to, so a case
# asserting only on DownloadProgress passes a download that wrote nothing.
if ls "$OUT"/downloads/* >/dev/null 2>&1; then
  pass=$((pass + 1))
  printf '  %-11s PASS  %s
' "dl-file" "$(ls "$OUT"/downloads | head -1)"
else
  fail=$((fail + 1))
  printf '  %-11s FAIL  bytes arrived but no file was written
' "dl-file"
fi

run_case api 'print_to_pdf|title: "script:2"' \
  WELD_SCRIPT='document.title = "script:" + (1 + 1)' \
  WELD_PDF="$OUT/api.pdf" \
  WELD_UA_PRODUCT=weld-battery \
  WELD_HISTORY=1

# CDP is execute_dev_tools_method, a different CEF call from the show_dev_tools
# window that crashes on 151. Assert the response, not just that nothing broke:
# a host building its own inspector pane depends on this path, not that one.
run_case cdp 'CDP <- .*"result"' WELD_CDP=Browser.getVersion
run_case visibility 'set_visible' WELD_HIDE_CYCLE=1
run_case devtools 'open_devtools' WELD_DEVTOOLS=1
run_case crash 'recovering from' WELD_CRASH_AFTER_SECS=4 WELD_RECOVER=1

echo
printf 'battery: %s pass, %s live, %s fail\n' "$pass" "$live" "$fail"
echo "logs in $OUT"
[ "$fail" -eq 0 ]
