#!/usr/bin/env bash
# Run the parity battery: one demo invocation per capability, and assert on
# what each one produced rather than on the demo merely having run.
#
# Usage, from the repo root, with CEF_PATH pointing at the CEF distribution:
#
#   RUN_CMD="cargo run -q -p demo-weld-linux" scripts/parity-battery.sh
#   RUN_CMD="cargo run -q -p demo-weld-win"   scripts/parity-battery.sh
#   RUN_CMD="./target/bundle/demo-weld-mac.app/Contents/MacOS/demo-weld-mac" \
#     scripts/parity-battery.sh
#
# macOS must run the bundled executable: CEF loads its framework relative to
# the .app, so `cargo run` cannot work there. Self-hosted macOS runners should
# also set WELD_MAC_APP to that bundle. The battery then uses LaunchServices,
# which places AppKit in the logged-in GUI session instead of the runner
# worker's idle process context.
#
# Four verdicts, because two of them are easy to confuse:
#
#   PASS  the case's own receipt appeared and nothing failed
#   LIVE  the run was clean but this case has no receipt of its own, so it
#         proves the path did not break, not that the capability works
#   SKIP  a named, documented platform limitation was excluded explicitly
#   FAIL  the page did not load, the demo reported a failure, or the expected
#         receipt never appeared
#
# LIVE is deliberately not PASS. A capability whose only evidence is "the demo
# did not crash" has not been verified, and rolling it up as a pass is how a
# table ends up claiming more than was measured.
#
# Do not edit this file while it is running. Bash reads a script by byte
# offset as it executes, so an edit mid-run shifts everything underneath the
# interpreter and silently reruns or garbles later cases.
set -u

REPO="$(cd "$(dirname "$0")/.." && pwd)"

# Chromium wants a real file URL. Under Git Bash the repo path is /c/Users/...,
# which Chromium resolves as relative and answers ERR_FILE_NOT_FOUND for, so
# every probe case silently loads an error page and still imports frames.
# cygpath -m gives C:/Users/... which is what the URL needs.
case "$(uname -s)" in
MINGW* | MSYS* | CYGWIN*) PROBES="file:///$(cygpath -m "$REPO")/testing" ;;
*) PROBES="file://$REPO/testing" ;;
esac

OUT="${WELD_BATTERY_OUT:-$REPO/target/battery}"

# Scripted input is a staged sequence on a clock, not a queue that drains as
# fast as it can. demo-weld-*/src/scripted.rs gates stage N on
# `SETTLE + GAP * N` elapsed since the page became ready, with SETTLE 3s and
# GAP 2s, so stage N fires at 3 + 2N seconds:
#
#   0 touch   4 page-drag   5 click   6 wheel   7 key
#   8 IME     9 hide       10 show   11 devtools  12 right-click
#
# The last stage therefore needs ~27s plus however long the page took to load.
# Anything shorter silently drops the late stages, and the case then looks like
# a broken capability rather than a short clock: at 16s this battery reported
# IME, visibility, devtools and context as failures, and all four were fine.
CASE_SECS="${WELD_CASE_SECS:-34}"
SKIP_CASES="${WELD_SKIP_CASES:-}"

: "${RUN_CMD:?set RUN_CMD to the demo invocation}"
: "${CEF_PATH:?set CEF_PATH to the CEF binary distribution}"
export CEF_PATH

# The demos do not agree on how they report. demo-weld-win uses eprintln!
# throughout, so it talks with no configuration; demo-weld-linux and
# demo-weld-mac put frame imports and navigation events behind `log`, which
# emits nothing at all unless RUST_LOG is set. Without this the battery sees
# only the eprintln! half on those two platforms and reports every title and
# frame receipt as missing, which reads exactly like a broken capability.
export RUST_LOG="${RUST_LOG:-info}"

mkdir -p "$OUT"
DOWNLOADS="$OUT/downloads-$$"
if [ -n "${WELD_CACHE_ROOT:-}" ]; then
  mkdir -p "$WELD_CACHE_ROOT"
elif [ -n "${WELD_PROFILE:-}" ]; then
  mkdir -p "$(dirname "$WELD_PROFILE")"
fi
echo "battery: $RUN_CMD"
echo "cef:     $CEF_PATH"
echo "out:     $OUT"
echo

pass=0
live=0
skip=0
fail=0

# run_case <name> <expect-regex|-> <env>...
run_case() {
  name="$1"
  expect="$2"
  shift 2
  log="$OUT/$name.log"

  case " $SKIP_CASES " in
  *" $name "*)
    skip=$((skip + 1))
    printf '  %-11s SKIP  documented platform limitation\n' "$name"
    return
    ;;
  esac

  # CEF subprocesses can outlive the browser process briefly. Reusing one
  # profile immediately makes the next case race the previous profile lock and
  # silently fall back to Default. Keep the root cache shared, but give every
  # case its own direct-child request-context profile. CEF rejects deeper
  # descendants and expects to create the final directory itself.
  profile_env=()
  if [ -n "${WELD_CACHE_ROOT:-}" ]; then
    process_root="$WELD_CACHE_ROOT"
    case "$(uname -s)" in
    MINGW* | MSYS* | CYGWIN*) process_root="$(cygpath -w "$WELD_CACHE_ROOT")" ;;
    esac
    case_profile="$process_root/$name"
    profile_env=("WELD_CACHE_ROOT=$process_root" "WELD_PROFILE=$case_profile")
  elif [ -n "${WELD_PROFILE:-}" ]; then
    process_profile="$WELD_PROFILE"
    case "$(uname -s)" in
    MINGW* | MSYS* | CYGWIN*) process_profile="$(cygpath -w "$WELD_PROFILE")" ;;
    esac
    profile_env=("WELD_PROFILE=$process_profile")
  fi

  if [ -n "${WELD_MAC_APP:-}" ]; then
    : >"$log"
    launch_env=()
    # LaunchServices does not inherit a shell's full environment. Forward the
    # exported demo configuration, then add this case's overrides explicitly.
    for key in $(compgen -e); do
      case "$key" in
      WELD_* | WGPU_* | CEF_PATH | RUST_LOG)
        launch_env+=("$key=${!key}")
        ;;
      esac
    done
    for assignment in "$@" "${profile_env[@]}" "WELD_TIMEOUT_SECS=$CASE_SECS"; do
      launch_env+=("$assignment")
    done
    bash "$REPO/scripts/run-weld-mac.sh" \
      "$WELD_MAC_APP" "$log" "$log" "$((CASE_SECS + 10))" \
      "${launch_env[@]}"
    code=$?
    # LaunchServices can finish one app instance while CEF helper processes are
    # still retiring. Intel macOS has then admitted the next process but left
    # it before browser creation for the whole case window. A clean run with no
    # browser-start receipt is a launcher failure, not a capability verdict, so
    # retry that exact condition once. A second miss still fails below.
    if [ "$code" -eq 0 ] && ! grep -q 'creating CEF browser' "$log" 2>/dev/null; then
      printf '  %-11s RETRY LaunchServices did not reach CEF browser creation\n' "$name"
      sleep "${WELD_MAC_RETRY_SETTLE_SECS:-2}"
      bash "$REPO/scripts/run-weld-mac.sh" \
        "$WELD_MAC_APP" "$log" "$log" "$((CASE_SECS + 10))" \
        "${launch_env[@]}"
      code=$?
    fi
  else
    env "$@" "${profile_env[@]}" WELD_TIMEOUT_SECS="$CASE_SECS" $RUN_CMD >"$log" 2>&1
    code=$?
  fi

  # A case whose page never loaded still imports frames, of the error page,
  # and would otherwise read as a pass.
  # ERR_ABORTED is not a load failure: a case that exits on a frame count tears
  # the browser down mid-navigation and Chromium reports the cancelled load.
  if grep 'LoadError' "$log" 2>/dev/null | grep -qv 'ERR_ABORTED'; then
    fail=$((fail + 1))
    printf '  %-11s FAIL  page did not load %s\n' \
      "$name" "$(grep -ohE 'error_text: "[^"]*"' "$log" | grep -v ERR_ABORTED | head -1)"
    return
  fi

  if grep -q 'Cannot create profile' "$log" 2>/dev/null; then
    fail=$((fail + 1))
    printf '  %-11s FAIL  CEF rejected the named profile and fell back to Default\n' "$name"
    return
  fi

  # The native DevTools window terminates accelerated windowless CEF on the
  # measured platforms. The safe behavior is a deliberate refusal while the
  # process stays alive. CDP is tested separately below.
  if [ "$name" = "devtools" ]; then
    refusal_line=$(grep -n 'open_devtools() failed:.*DevTools windows are disabled for windowless CEF' "$log" 2>/dev/null | tail -1 | cut -d: -f1)
    post_refusal_frame=""
    if [ -n "$refusal_line" ]; then
      post_refusal_frame=$(tail -n "+$((refusal_line + 1))" "$log" | grep -m1 'imported frame #' 2>/dev/null)
    fi
    if [ "$code" -eq 0 ] && \
       [ -n "$post_refusal_frame" ] && \
       ! grep -q 'open_devtools() ok' "$log" 2>/dev/null; then
      pass=$((pass + 1))
      printf '  %-11s PASS  refusal followed by imported frame\n' "$name"
    else
      fail=$((fail + 1))
      printf '  %-11s FAIL  expected safe DevTools refusal, exit=%s\n' "$name" "$code"
    fi
    return
  fi

  # Match the whole line after "failed", not a restricted character class: the
  # macOS DevTools refusal reads `open_devtools() failed: ...`, and parentheses
  # are enough to slip past a tighter pattern and report a refusal as a pass.
  # Focus is deferred until the first imported frame, so a move_focus failure
  # is now actionable and belongs in the verdict like every other host call.
  failed=$({
    grep -ohE 'weld demo: [^:]*failed[^;]*' "$log" 2>/dev/null
    grep -ohE 'VALIDATION FAIL[^;]*|PIXEL FIXTURE FAIL[^;]*|pixel-fixture: FAIL[^;]*' "$log" 2>/dev/null
  } | sort -u | cut -c1-90 | tr '\n' ';')
  if [ -n "$failed" ] || [ "$code" -ne 0 ]; then
    fail=$((fail + 1))
    printf '  %-11s FAIL  exit=%s %s\n' "$name" "$code" "${failed:-(no failure line)}"
    return
  fi

  if [ "$expect" = "-" ]; then
    live=$((live + 1))
    printf '  %-11s LIVE  ran clean, no receipt of its own\n' "$name"
    return
  fi

  got=$(grep -ohE "$expect" "$log" 2>/dev/null | sort -u | tail -2 | tr '\n' ';' | cut -c1-110)
  if [ -n "$got" ]; then
    pass=$((pass + 1))
    printf '  %-11s PASS  %s\n' "$name" "$got"
  else
    fail=$((fail + 1))
    printf '  %-11s FAIL  expected /%s/, absent\n' "$name" "$expect"
  fi
}

# The animated fixture produces enough paints for every backend to reach two
# imported frames, then makes the native-texture readback affect process status.
# A redraw-count exit is not an import receipt: the host can draw its clear
# colour repeatedly while CEF has delivered zero native textures.
run_case import 'PIXEL FIXTURE PASS|VALIDATION PASS|pixel-fixture: PASS' \
  WELD_PIXEL_FIXTURE=1 WELD_EXIT_AFTER_FRAMES=2

run_case input 'title: "(key|wheel):[^"]*"' \
  WELD_URL="$PROBES/weld_input_probe.html" \
  WELD_CLICK_AT=120,120 WELD_WHEEL=400 WELD_KEY=a

run_case popup 'imported popup' WELD_URL="$PROBES/weld_select_probe.html" WELD_CLICK_AT=60,40
run_case find 'weld demo: find ' WELD_URL="$PROBES/weld_find_probe.html" WELD_FIND=needle
run_case zoom 'zoom level now|title: "w:[0-9]+"' WELD_URL="$PROBES/weld_zoom_probe.html" WELD_ZOOM=1
# The IME probe reports each phase, not the bare text: cstart:, cupdate:weld,
# cend:weld, textinput:weld, value:weld. Assert the committed value.
run_case ime 'title: "(value|textinput|cend):weld"' WELD_URL="$PROBES/weld_ime_probe.html" WELD_IME=weld
run_case context 'scripted right-click at' WELD_URL="$PROBES/weld_context_probe.html" WELD_RIGHT_CLICK_AT=60,40
run_case touch 'scripted touch at' WELD_URL="$PROBES/weld_drag_touch_probe.html" WELD_TOUCH_AT=120,120

# The drag must start on the probe's draggable element, which is fixed at CSS
# 500,350. Starting anywhere else grabs nothing, CEF never emits DragStarted,
# and the finish step it gates never runs. WELD_SCALE=1 pins physical pixels to
# CSS pixels so one coordinate is right on 1x and 2x panels alike.
run_case drag 'page drag finished as copy|title: "PAGE_DRAG:started"' \
  WELD_URL="$PROBES/weld_drag_touch_probe.html" \
  WELD_SCALE=1 WELD_PAGE_DRAG=520,370,620,420 WELD_FINISH_PAGE_DRAG=1

run_case download 'DownloadProgress \{[^}]*bytes_received' \
  WELD_URL="$PROBES/weld_download_probe.html" \
  WELD_CLICK_AT=60,40 WELD_DOWNLOAD_DIR="$DOWNLOADS"

# The byte count is not the receipt; the file is. CEF reports 28 of 28 bytes
# for a transfer it never completes and never assigns a path to, so a case
# asserting only on DownloadProgress passes a download that wrote nothing.
case " $SKIP_CASES " in
*" download "*)
  skip=$((skip + 1))
  printf '  %-11s SKIP  download case was skipped\n' "dl-file"
  ;;
*)
  if ls "$DOWNLOADS"/* >/dev/null 2>&1; then
    pass=$((pass + 1))
    printf '  %-11s PASS  %s\n' "dl-file" "$(ls "$DOWNLOADS" | head -1)"
  else
    fail=$((fail + 1))
    printf '  %-11s FAIL  bytes arrived but no file was written\n' "dl-file"
  fi
  ;;
esac

run_case api 'print_to_pdf|title: "script:2"' \
  WELD_URL="$PROBES/weld_anim_probe.html" \
  WELD_SCRIPT='document.title = "script:" + (1 + 1)' \
  WELD_PDF="$OUT/api.pdf" \
  WELD_UA_PRODUCT=weld-battery \
  WELD_HISTORY=1

# These IDs are deliberately one step beyond u32. The completion receipt proves
# the caller's full u64 identity crossed the browser/renderer process boundary
# and returned through the unified event stream without narrowing.
run_case script-id 'SCRIPT #4294967296|script #4294967296' \
  WELD_URL="$PROBES/weld_anim_probe.html" \
  WELD_SCRIPT='({title: document.title, n: 2+2})'

run_case cookie-id 'COOKIES #4294967297|cookies #4294967297' \
  WELD_URL="$PROBES/weld_anim_probe.html" \
  WELD_COOKIE_URL="https://example.com/"

# CDP is execute_dev_tools_method, a different CEF call from the show_dev_tools
# window that crashes on 151. Assert its response and the safe window refusal:
# a host building its own inspector pane depends on CDP, not the native window.
run_case cdp 'CDP <- .*"result"' \
  WELD_URL="$PROBES/weld_anim_probe.html" WELD_CDP=Browser.getVersion
run_case visibility 'set_visible' \
  WELD_URL="$PROBES/weld_anim_probe.html" WELD_HIDE_CYCLE=1
run_case devtools 'open_devtools' \
  WELD_URL="$PROBES/weld_anim_probe.html" WELD_DEVTOOLS=1
run_case crash 'recovering from' WELD_CRASH_AFTER_SECS=4 WELD_RECOVER=1

echo
printf 'battery: %s pass, %s live, %s skip, %s fail\n' "$pass" "$live" "$skip" "$fail"
echo "logs in $OUT"
[ "$fail" -eq 0 ]
